import java.awt.event.KeyEvent;
import javax.swing.text.DefaultCaret;

public class ClientUI extends javax.swing.JFrame {

    private static Client client;
    private static boolean isRunning = true;

    public ClientUI() {
        initComponents();
        spnPort.setValue(1500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCheckConnected = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnClientSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaClientOut = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaClientOut1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        spnPort = new javax.swing.JSpinner();
        txfEnterUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnJoin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txfServer = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txfClientMsg = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Client");
        setMinimumSize(new java.awt.Dimension(491, 484));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(235, 233, 233));

        btnCheckConnected.setText("Online users");
        btnCheckConnected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckConnected.setEnabled(false);
        btnCheckConnected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckConnectedActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setEnabled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnClientSend.setText("Send");
        btnClientSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientSend.setEnabled(false);
        btnClientSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientSendActionPerformed(evt);
            }
        });

        txaClientOut.setEditable(false);
        txaClientOut.setColumns(20);
        txaClientOut.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txaClientOut.setLineWrap(true);
        txaClientOut.setRows(5);
        txaClientOut.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaClientOut);

        txaClientOut1.setEditable(false);
        txaClientOut1.setColumns(20);
        txaClientOut1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txaClientOut1.setRows(5);
        jScrollPane2.setViewportView(txaClientOut1);

        jPanel2.setBackground(new java.awt.Color(57, 186, 199));

        spnPort.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txfEnterUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEnterUsernameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel2.setText("Port number");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Enter username:");

        btnJoin.setText("Join");
        btnJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel3.setText("Server");

        txfServer.setText("localhost");
        txfServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txfEnterUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spnPort, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfServer, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfEnterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txfServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        txfClientMsg.setColumns(20);
        txfClientMsg.setLineWrap(true);
        txfClientMsg.setRows(5);
        txfClientMsg.setWrapStyleWord(true);
        txfClientMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfClientMsgKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(txfClientMsg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClientSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckConnected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClientSend, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheckConnected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout))
                    .addComponent(jScrollPane3))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientSendActionPerformed
        send();
    }//GEN-LAST:event_btnClientSendActionPerformed

    private void send() {
        String msg = txfClientMsg.getText().trim();
        txfClientMsg.setText("");
        client.sendMessage(new ChatMessage(ChatMessage.MESSAGE, msg));
    }

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        DefaultCaret caret = (DefaultCaret)txaClientOut.getCaret();
        caret.setUpdatePolicy(DefaultCaret.OUT_BOTTOM);
        String username = txfEnterUsername.getText().trim();
        String serverAddress = txfServer.getText().trim();
        if (username.equals("")) {
            txaClientOut.setText(" *** Please enter a username. *** ");
        } else if (serverAddress.equals("")) {
            txaClientOut.append(" *** Please enter a server address. *** ");
        } else {
            int portNumber = (int) spnPort.getValue();
            client = new Client(serverAddress, portNumber, username);
            if (!client.start()) {
                txaClientOut.setText(" *** Error starting client *** \n");
            } else {
                String initialMessage = client.readMessage();
                if (initialMessage.equals("true")) {
                    client.startListeningFromServer();
                    txaClientOut.setText("Welcome to the chatroom.\n");
                    txaClientOut.append("To broadcast a message to all connected users just type a message\nand press send.\n");
                    txaClientOut.append("To send a private message, type @<username> <message>.\n\n");
                    btnClientSend.setEnabled(true);
                    txfEnterUsername.setEditable(false);
                    btnJoin.setEnabled(false);
                    btnLogout.setEnabled(true);
                    btnCheckConnected.setEnabled(true);
                    spnPort.setEnabled(false);
                } else if (initialMessage.equals("false")) {
                    txaClientOut.setText("This username already exists. Try using a new one.");
                }
            }
        }
    }//GEN-LAST:event_btnJoinActionPerformed


    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        close();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void close() {
        isRunning = false;
        client.disconnect();
        setVisible(false);
        dispose();
        System.exit(0);
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close();
    }//GEN-LAST:event_formWindowClosing

    private void btnCheckConnectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckConnectedActionPerformed
        String msg = txfClientMsg.getText().trim();
        txfClientMsg.setText("");
        client.sendMessage(new ChatMessage(ChatMessage.WHOISIN, ""));
    }//GEN-LAST:event_btnCheckConnectedActionPerformed

    private void txfEnterUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEnterUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEnterUsernameActionPerformed

    private void txfClientMsgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfClientMsgKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            send();
        }
    }//GEN-LAST:event_txfClientMsgKeyPressed

    private void txfServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUI().setVisible(true);
            }
        });
    }

    public static void printToOut(String msg) {
        txaClientOut.append("> " + msg + "\n");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckConnected;
    private javax.swing.JButton btnClientSend;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner spnPort;
    private static javax.swing.JTextArea txaClientOut;
    private static javax.swing.JTextArea txaClientOut1;
    private javax.swing.JTextArea txfClientMsg;
    private javax.swing.JTextField txfEnterUsername;
    private javax.swing.JTextField txfServer;
    // End of variables declaration//GEN-END:variables
}
